version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: account-manager:develop
    container_name: account-manager
    env_file:
     - app.env
    ports:
      - "8080:8080"
    networks:
      - db-network

networks:
  db-network:
    external: true